### ISSUE TITLE
Relax required Node.js engine version

### ISSUE THREAD

**Issue by vitallium** [silentroach/tweet.md#11]
Hello, I stumbled upon the problem with the required Node.js engine version.

`package.json` specifies `"node": "^6.0.0"` but we use >= 12. Installing this package with Node.js 12 fails due to required Node.js engine version.
For example:

```
error tweet.md@2.2.1: The engine "node" is incompatible with this module. Expected version "^6.0.0". Got "12.14.1"
error Found incompatible module.
```

I didn't found any blockers on updating or removing the required Node.js version.

What're possible resolutions here?

Thanks!

**Comment by silentroach** [comment]
thanks for you report, now it is `>=8.0.0`, please try it now (tweet.md@3.0.0)

**Comment by vitallium** [comment]
@silentroach, that was fast! It works like a charm now. Thank you! 🙇
