### ISSUE TITLE
Support for new labs format

### ISSUE THREAD

**Issue by Jovin-Ang** [silentroach/tweet.md#12]
Twitter launched the new labs program last year and the tweet format differs from the existing production api. Since labs' endpoint is set to be the future of twitter api, we can maintain another branch for parsing the tweet objects from the labs endpoint.
https://developer.twitter.com/en/docs/labs/overview/whats-new/formats

**Comment by silentroach** [comment]
Hi, thank you for your request. Can you explain what is the difference between old and new format? Or maybe provide an example, when tweet.md will fail to render tweet.

**Comment by Jovin-Ang** [comment]
The new labs tweet format has several differences from the existing one. All the fields are documented here: https://developer.twitter.com/en/docs/labs/tweets-and-users/api-reference/get-tweets-v1

For example, the `quoted_status` field is gone. To detect a quoted tweet, one has to detect the presence of `referenced_tweets` field and check that `referenced_tweets.type` value is `quoted`. The quoted tweet full text is then included in the `includes.tweets` field.

Another thing is `full_text` is gone. `id_str` is gone and now `id` is always a string. `entities.indices` is gone, replaced by `entities.<type>.start` and `entities.<type>.end`

In a separate matter, The current tweet parser seems to have a minor bug where is a link is after an emoji, it fails to parse, leaving a h in front.

**For example the following tweet:**
Twitter libraries are a great way to use our API. Did you know:
✨ 100+ libraries support the Twitter API
✨ In 25+ programming languages 🐍☕️♦️ 
Explore our curated list of community built libraries 📚
https://t.co/mgXiWmt9SY

**Got parsed to:**

Twitter libraries are a great way to use our API. Did you know:

✨ 100+ libraries support the Twitter API
✨ In 25+ programming languages 🐍☕️♦️   

Explore our curated list of community built libraries 📚  

h[developer.twitter.com/en/docs/develo…](https://t.co/mgXiWmt9SY "https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries")

**Comment by silentroach** [comment]
Thank, will check it

>The current tweet parser seems to have a minor bug where is a link is after an emoji
It is better to split it in another issue, can you give me this tweet json or link?

**Comment by silentroach** [comment]
https://github.com/silentroach/tweet.md/issues/13
