### ISSUE TITLE
Minor bug in parsing links after emoji

### ISSUE THREAD

**Issue by Jovin-Ang** [silentroach/tweet.md#13]
https://twitter.com/TwitterDev/status/1225458878277705728

The current tweet parser seems to have a minor bug where is a link is after an emoji, it fails to parse, leaving a h in front.

**For example the following tweet:**
Twitter libraries are a great way to use our API. Did you know:
✨ 100+ libraries support the Twitter API
✨ In 25+ programming languages 🐍☕️♦️ 
Explore our curated list of community built libraries 📚
https://t.co/mgXiWmt9SY

**Got parsed to:**

Twitter libraries are a great way to use our API. Did you know:

✨ 100+ libraries support the Twitter API
✨ In 25+ programming languages 🐍☕️♦️   

Explore our curated list of community built libraries 📚  

h[developer.twitter.com/en/docs/develo…](https://t.co/mgXiWmt9SY "https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries")

**Comment by silentroach** [comment]
Thanks for you report, tweet processing was totally wrong, now it should be fine
