### ISSUE TITLE
remember broken rendering with …?

### ISSUE THREAD

**Issue by iamstarkov** [silentroach/tweet.md#5]
> ### Entities for Retweets

> From the Twitter API perspective, a Retweet is a special kind of Tweet that contains the original Tweet as an embedded retweeted_status object. For consistency, the top-level Retweet object also has a text property and associated entities.

> The Retweet text attribute is composed of the original Tweet text with “RT @username: ” prepended. If the display character count then exceeds 140 characters, this text is truncated and an ellipsis “…” is added. **Consequently, some top-level entities might be incorrect or missing, for instance in the case of a truncated hashtag entry.**

> **As a result, the best practice is to retrieve the text, entities, original author and date from the original Tweet in retweeted_status whenever this exists.**

> — https://dev.twitter.com/overview/api/entities-in-twitter-objects#media

**Comment by silentroach** [comment]
А не помнишь где это было?

**Comment by silentroach** [comment]
Тут ведь ещё есть вопрос - действительно ли эта библиотека должна делать или разработчик, который ее юзает.
Не брать же на себя решение о том, как именно должен выглядеть итоговый ретвит?

**Comment by iamstarkov** [comment]
надо искать по `...` на jsunderhood (мб до сегодняшних обновлений)

**Comment by iamstarkov** [comment]
мне кажется это должна делать библиотека, так как библиотеке отдают твит на маркдаун рендер: всё норм, что она рендерит сам твит, но при этом если он будет битым, хотя в апи написано как это чинить, то кажется этим должна заниматься библиотека

**Comment by iamstarkov** [comment]
что думаешь?

**Comment by silentroach** [comment]
RT @nick просто самому придётся добавлять
Вечером сегодня или завтра посмотрю

**Comment by iamstarkov** [comment]
нова. рендерит тело твита надо из текста прошенного твита. а вот индексы ентитсов надо брать из retweeted_status

**Comment by silentroach** [comment]
В тех entities позиции относительно оригинального твита, а не того, что получилось

**Comment by silentroach** [comment]
вижу, ты в jsunderhood так и сделал - если есть retweeted_status, то рендеришь его.
это и есть правильный путь, на мой взгляд

**Comment by iamstarkov** [comment]
йеп

**Comment by silentroach** [comment]
может и тут сделать так же - если есть retweeted_status - рендерить его и обрамлять как цитату?

**Comment by iamstarkov** [comment]
я просто подумал, что можно как-то применить знание о поломанных индексах в ретвитах

**Comment by iamstarkov** [comment]
обрамлять как цитату — плохая идея, так как плохо композируется с другими инструментами

**Comment by silentroach** [comment]
применить знание можно только зная смещение относительно оригинала, а высчитать его можно только хаком с поиском в ретвите начала оригинального текста, что так себе

**Comment by silentroach** [comment]
м, дополнить тогда цитату будет не очень удобно, как в твоем случае с картинками

**Comment by silentroach** [comment]
почешу репу еще

**Comment by iamstarkov** [comment]
закрою, пока не найдём подходящий тесткейс
